name: Generated files
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Sync project dependency files
        run: yarn sync
      - name: Push generated artifacts to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Our git status is not clean. Checking in the following files:";
            echo "$(git status --porcelain)";
            git config --global credential.helper 'cache --timeout=120'
            git config --global user.email "carbon@us.ibm.com"
            git config --global user.name "carbon-bot"
            git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/carbon-design-system/carbon.git"
            git checkout master
            git add -A
            git commit -m "chore(project): sync generated files"
            git push
          fi
